services:
  db:
    build: .
    container_name: teste-db
    restart: always
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=teste
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
    driver: local
